CREATE TABLE IF NOT EXISTS counter (id INTEGER PRIMARY KEY CHECK(id=1), total INTEGER NOT NULL DEFAULT 0);
INSERT OR IGNORE INTO counter(id,total) VALUES(1,0);
CREATE TABLE IF NOT EXISTS visits (day TEXT NOT NULL, token TEXT NOT NULL, PRIMARY KEY(day,token));
CREATE TRIGGER IF NOT EXISTS count_visit AFTER INSERT ON visits BEGIN
 UPDATE counter SET total=total+1 WHERE id=1;
END;
